# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-26 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_auto_20211026_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, default=0)),
                ('design_average', models.FloatField(blank=True, default=0)),
                ('usability_average', models.FloatField(blank=True, default=0)),
                ('content_average', models.FloatField(blank=True, default=0)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_rating', to='reviewer.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='rating',
            name='content_average',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='design_average',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='post',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='score',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='usability_average',
        ),
        migrations.AddField(
            model_name='rating',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='reviewer.Project'),
        ),
    ]
