# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-26 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0004_auto_20211026_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrating',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectrating', to='reviewer.Project'),
        ),
    ]
